export const countries = [
  { value: 'AUS', label: 'Australia', currency: 'AUD' },
  { value: 'BRA', label: 'Brazil', currency: 'BRL' },
  { value: 'CAN', label: 'Canada', currency: 'CAD' },
  { value: 'CHN', label: 'China', currency: 'CNY' },
  { value: 'DEU', label: 'Germany', currency: 'EUR' },
  { value: 'FRA', label: 'France', currency: 'EUR' },
  { value: 'IND', label: 'India', currency: 'INR' },
  { value: 'JPN', label: 'Japan', currency: 'JPY' },
  { value: 'NPL', label: 'Nepal', currency: 'NPR' },
  { value: 'NGA', label: 'Nigeria', currency: 'NGN' },
  { value: 'SGP', label: 'Singapore', currency: 'SGD' },
  { value: 'ZAF', label: 'South Africa', currency: 'ZAR' },
  { value: 'ARE', label: 'United Arab Emirates', currency: 'AED' },
  { value: 'GBR', label: 'United Kingdom', currency: 'GBP' },
  { value: 'USA', label: 'United States', currency: 'USD' },
];
