import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Logo } from '@/components/logo';
import {
  Bot,
  BrainCircuit,
  DatabaseZap,
  Filter,
  Gauge,
  LayoutTemplate,
  Scissors,
} from 'lucide-react';

const steps = [
  {
    title: 'Step 1: Data Sourcing',
    content:
      'In this first step, we collect relevant data from multiple sources that will form the core of your Gen AI project. The gathered data will be processed, analyzed, and fed into the pipeline to enable the AI system to make informed, contextually accurate decisions.',
    icon: <DatabaseZap className="h-5 w-5" />,
  },
  {
    title: 'Step 2: Data Preprocessing',
    content:
      'In this step, raw data is cleaned and organized for better quality and usability. This may include removing noise, correcting errors, and structuring the data so that it can be easily processed by the AI model.',
    icon: <Filter className="h-5 w-5" />,
  },
  {
    title: 'Step 3: Splitting & Chunking',
    content:
      'This step involves breaking down large data (documents or text) into smaller chunks to improve processing efficiency. The goal is to make the data manageable and maintain context for meaningful retrieval and response generation.',
    icon: <Scissors className="h-5 w-5" />,
  },
  {
    title: 'Step 4: Embeddings & Knowledge Base',
    content:
      "In this step, textual data is converted into numerical representations called embeddings, capturing the semantic meaning of the text. These embeddings are stored in a vector database, which serves as a centralized knowledge base. This knowledge base becomes the AI system's primary source for retrieving relevant information efficiently.",
    icon: <BrainCircuit className="h-5 w-5" />,
  },
  {
    title: 'Step 5: AI Query Processing',
    content:
      'This step involves processing user queries, retrieving relevant data from the knowledge base, and using an AI engine (like GPT or other LLMs) to generate a context-aware response.',
    icon: <Bot className="h-5 w-5" />,
  },
  {
    title: 'Step 6: UI & Deployment',
    content:
      'This step focuses on building the user interface (UI) and deploying the application for production use. The goal is to create an intuitive, user-friendly interface that allows users to interact with the AI system easily, while ensuring the system is scalable and reliable through deployment in the cloud.',
    icon: <LayoutTemplate className="h-5 w-5" />,
  },
  {
    title: 'Step 7: Testing & Optimization',
    content:
      "This step focuses on testing the complete pipeline and optimizing various components to ensure efficient performance and accurate results. This involves evaluating the functionality, improving the system's speed and responsiveness, and enhancing the quality of responses generated by the AI. Additionally, specialized tools and frameworks are used to evaluate the effectiveness of the RAG pipeline and optimize it for better results.",
    icon: <Gauge className="h-5 w-5" />,
  },
];

export function WelcomeSplash() {
  return (
    <div className="flex flex-col items-center justify-center h-full p-8 text-center bg-card rounded-xl border-2 border-dashed">
      <div className="mb-6">
        <Logo />
      </div>
      <h2 className="text-3xl font-bold mb-2">How Our AI Works</h2>
      <p className="text-muted-foreground max-w-2xl mb-10">
        Our system follows a sophisticated pipeline to deliver intelligent and
        accurate resume analysis. Here’s a breakdown of the key stages involved
        in our Generative AI-powered process.
      </p>
      <div className="w-full max-w-4xl text-left">
        <Accordion type="single" collapsible className="w-full">
          {steps.map((step, index) => (
            <AccordionItem value={`item-${index + 1}`} key={index}>
              <AccordionTrigger>
                <div className="flex items-center gap-3">
                  <span className="text-primary">{step.icon}</span>
                  <span className="font-semibold">{step.title}</span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pl-11 text-muted-foreground">
                {step.content}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </div>
  );
}
