'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/generate-resume-match-score.ts';
import '@/ai/flows/extract-resume-information-flow.ts';
import '@/ai/flows/generate-hiring-recommendations.ts';
import '@/ai/flows/predict-salary-range.ts';
import '@/ai/flows/generate-career-personality-profile.ts';
import '@/ai/flows/analyze-video-resume.ts';
import '@/ai/flows/predict-work-life-balance.ts';
import '@/ai/flows/find-networking-opportunities.ts';
import '@/ai/flows/rewrite-resume-flow.ts';
import '@/ai/flows/roast-resume-flow.ts';
import '@/ai/flows/confidence-booster-flow.ts';
import '@/ai/flows/personal-brand-check-flow.ts';
import '@/ai/flows/hidden-strength-discovery-flow.ts';
import '@/ai/flows/career-risk-assessment-flow.ts';
import '@/ai/flows/skill-obsolescence-warning-flow.ts';
import '@/ai/flows/resume-version-control-flow.ts';
import '@/ai/flows/internship-readiness-flow.ts';
import '@/ai/flows/candidate-ranking-flow.ts';
import '@/ai/flows/team-benchmarking-flow.ts';
import '@/ai/flows/hiring-funnel-insights-flow.ts';
import '@/ai/flows/country-resume-rules-flow.ts';
import '@/ai/flows/visa-sponsorship-flow.ts';
import '@/ai/flows/project-idea-generator-flow.ts';
import '@/ai/flows/certification-suggestion-flow.ts';
import '@/ai/flows/course-recommendation-flow.ts';
import '@/ai/flows/side-hustle-recommendation-flow.ts';
import '@/ai/flows/freelance-pricing-estimator-flow.ts';
import '@/ai/flows/personal-swot-analysis-flow.ts';
import '@/ai/flows/strength-to-career-mapping-flow.ts';
import '@/ai/flows/skill-stack-optimizer-flow.ts';
import '@/ai/flows/time-to-employability-flow.ts';
import '@/ai/flows/career-plan-generator-flow.ts';
